#!/usr/bin/env python3

# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibonacci(a0=1,a1=2,cap=4000000):
    if a1<=cap:
        return (a1%2==0)*a1+fibonacci(a1,a0+a1)
    else:
        return 0

def fibonacci_even(a0=0,a1=2,cap=4000000):
    if a1<=cap:
        return a1+fibonacci_even(a1,4*a1+a0)
    else:
        return 0

if __name__=="__main__":
    print('Sum is:{}'.format(fibonacci()))
    print('Sum is:{}'.format(fibonacci_even()))